name: flutter_inventory_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # This is a stable SDK constraint that works with your packages.
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your project's packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.20.2
  cloud_firestore: ^6.0.2
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add this assets section
  assets:
    - .env